# Version 값 임의변경 금지
Version: 1

Messages:
  Buy_Success: "&a성공적으로 구매하였습니다."
  Sell_Success: "&a성공적으로 판매하였습니다."
  Insufficient_Balance: "&c잔고가 부족합니다."
  Insufficient_Item_To_Sell: "&c판매 할 아이템이 부족합니다."

Menu:
  ProductItem_Lore:
    - "&6구매가격: &f{buy_price}원"
    - "&6판매가격: &f{sell_price}원"
    - ""
    - "&e좌클릭: &f1개 구매 | &e쉬프트 + 좌클릭: &f한 세트 구매"
    - "&e우클릭: &f1개 판매 | &e쉬프트 + 우클릭: &f모두 판매"